import { BenchmarkConfig } from '@/types/benchmark';

export function buildCliArgs(config: BenchmarkConfig): string[] {
  const args: string[] = [];

  if (config.baseUrl) {
    args.push('--base-url', config.baseUrl);
  }

  if (config.apiKey && config.apiKey !== 'EMPTY') {
    args.push('--api-key', config.apiKey);
  }

  if (config.model && config.model.trim()) {
    args.push('--model', config.model.trim());
  }

  if (config.servedModelName && config.servedModelName.trim()) {
    args.push('--served-model-name', config.servedModelName.trim());
  }

  if (config.tokenizer && config.tokenizer.trim()) {
    args.push('--tokenizer', config.tokenizer.trim());
  }

  if (config.pp && config.pp.length > 0) {
    args.push('--pp', ...config.pp.map(String));
  }

  if (config.tg && config.tg.length > 0) {
    args.push('--tg', ...config.tg.map(String));
  }

  if (config.exactTg) {
    args.push('--exact-tg');
  }

  if (config.depth && config.depth.length > 0) {
    args.push('--depth', ...config.depth.map(String));
  }

  if (config.runs !== undefined && config.runs !== 3) {
    args.push('--runs', String(config.runs));
  }

  if (config.warmupRuns !== undefined && config.warmupRuns !== 1) {
    args.push('--warmup-runs', String(config.warmupRuns));
  }

  if (config.noWarmup) {
    args.push('--no-warmup');
  }

  if (config.concurrency && config.concurrency.length > 0 && !(config.concurrency.length === 1 && config.concurrency[0] === 1)) {
    args.push('--concurrency', ...config.concurrency.map(String));
  }

  if (config.latencyMode && config.latencyMode !== 'generation') {
    args.push('--latency-mode', config.latencyMode);
  }

  if (config.noAdaptPrompt) {
    args.push('--no-adapt-prompt');
  }

  if (config.noCache) {
    args.push('--no-cache');
  }

  if (config.enablePrefixCaching) {
    args.push('--enable-prefix-caching');
  }

  if (config.skipCoherence) {
    args.push('--skip-coherence');
  }

  if (config.bookUrl && config.bookUrl.trim()) {
    args.push('--book-url', config.bookUrl.trim());
  }

  if (config.datasetFile && config.datasetFile.trim()) {
    args.push('--dataset-file', config.datasetFile.trim());
  }

  if (config.outputFormat && config.outputFormat !== 'md') {
    args.push('--format', config.outputFormat);
  }

  if (config.saveResult && config.saveResult.trim()) {
    args.push('--save-result', config.saveResult.trim());
  }

  if (config.saveTotalThroughputTimeseries) {
    args.push('--save-total-throughput-timeseries');
  }

  if (config.saveAllThroughputTimeseries) {
    args.push('--save-all-throughput-timeseries');
  }

  if (config.sampleInterval && config.sampleInterval !== 1.0) {
    args.push('--sample-interval', String(config.sampleInterval));
  }

  if (config.exitOnFirstFail) {
    args.push('--exit-on-first-fail');
  }

  if (config.noResultsOnFail) {
    args.push('--no-results-on-fail');
  }

  if (config.verbose) {
    args.push('--verbose');
  }

  if (config.postRunCmd && config.postRunCmd.trim()) {
    args.push('--post-run-cmd', `"${config.postRunCmd.trim()}"`);
  }

  if (config.extraBody && config.extraBody.trim()) {
    args.push('--extra-body', `"${config.extraBody.trim()}"`);
  }

  if (config.emitProgress) {
    args.push('--emit-progress', '-');
  }

  return args;
}

export function generateFullCommands(config: BenchmarkConfig) {
  const args = buildCliArgs({ ...config, emitProgress: false });
  const rawArgStr = args.join(' ');
  const formattedArgs = args
    .reduce<string[][]>((acc, curr, idx) => {
      if (curr.startsWith('--') || idx === 0) {
        acc.push([curr]);
      } else {
        if (acc.length > 0) {
          acc[acc.length - 1].push(curr);
        } else {
          acc.push([curr]);
        }
      }
      return acc;
    }, [])
    .map(chunk => `  ${chunk.join(' ')}`)
    .join(' \\\n');

  return {
    cli: `llama-benchy \\\n${formattedArgs}`,
    uvx: `uvx --from git+https://github.com/eugr/llama-benchy llama-benchy \\\n${formattedArgs}`,
    uvxPypi: `uvx llama-benchy \\\n${formattedArgs}`,
    python: `python -m llama_benchy \\\n${formattedArgs}`,
    singleLine: `llama-benchy ${rawArgStr}`,
    script: `#!/usr/bin/env bash\n# Generated by AI-Benchy\nset -euo pipefail\n\nllama-benchy \\\n${formattedArgs}\n`,
  };
}

export function parseCliStringToConfig(cliString: string, baseConfig: BenchmarkConfig): Partial<BenchmarkConfig> {
  const tokens = cliString
    .replace(/\\\n/g, ' ')
    .replace(/\\/g, ' ')
    .trim()
    .split(/\s+/)
    .filter(t => t.length > 0);

  const parsed: Partial<BenchmarkConfig> = {};
  let i = 0;

  // skip command name if present
  if (tokens[0] === 'llama-benchy' || tokens[0] === 'uvx' || tokens[0] === 'python') {
    while (i < tokens.length && !tokens[i].startsWith('--')) {
      i++;
    }
  }

  while (i < tokens.length) {
    const token = tokens[i];
    if (token === '--base-url' && tokens[i + 1]) {
      parsed.baseUrl = tokens[++i];
    } else if (token === '--api-key' && tokens[i + 1]) {
      parsed.apiKey = tokens[++i];
    } else if (token === '--model' && tokens[i + 1]) {
      parsed.model = tokens[++i];
    } else if (token === '--served-model-name' && tokens[i + 1]) {
      parsed.servedModelName = tokens[++i];
    } else if (token === '--tokenizer' && tokens[i + 1]) {
      parsed.tokenizer = tokens[++i];
    } else if (token === '--pp') {
      const pps: number[] = [];
      i++;
      while (i < tokens.length && !tokens[i].startsWith('--')) {
        const val = parseInt(tokens[i], 10);
        if (!isNaN(val)) pps.push(val);
        i++;
      }
      i--; // adjust loop increment
      if (pps.length > 0) parsed.pp = pps;
    } else if (token === '--tg') {
      const tgs: number[] = [];
      i++;
      while (i < tokens.length && !tokens[i].startsWith('--')) {
        const val = parseInt(tokens[i], 10);
        if (!isNaN(val)) tgs.push(val);
        i++;
      }
      i--;
      if (tgs.length > 0) parsed.tg = tgs;
    } else if (token === '--depth') {
      const depths: number[] = [];
      i++;
      while (i < tokens.length && !tokens[i].startsWith('--')) {
        const val = parseInt(tokens[i], 10);
        if (!isNaN(val)) depths.push(val);
        i++;
      }
      i--;
      if (depths.length > 0) parsed.depth = depths;
    } else if (token === '--concurrency') {
      const concs: number[] = [];
      i++;
      while (i < tokens.length && !tokens[i].startsWith('--')) {
        const val = parseInt(tokens[i], 10);
        if (!isNaN(val)) concs.push(val);
        i++;
      }
      i--;
      if (concs.length > 0) parsed.concurrency = concs;
    } else if (token === '--runs' && tokens[i + 1]) {
      parsed.runs = parseInt(tokens[++i], 10) || 3;
    } else if (token === '--warmup-runs' && tokens[i + 1]) {
      parsed.warmupRuns = parseInt(tokens[++i], 10) || 1;
    } else if (token === '--exact-tg') {
      parsed.exactTg = true;
    } else if (token === '--no-warmup') {
      parsed.noWarmup = true;
    } else if (token === '--no-cache') {
      parsed.noCache = true;
    } else if (token === '--no-adapt-prompt') {
      parsed.noAdaptPrompt = true;
    } else if (token === '--enable-prefix-caching') {
      parsed.enablePrefixCaching = true;
    } else if (token === '--skip-coherence') {
      parsed.skipCoherence = true;
    } else if (token === '--latency-mode' && tokens[i + 1]) {
      parsed.latencyMode = tokens[++i] as any;
    } else if (token === '--book-url' && tokens[i + 1]) {
      parsed.bookUrl = tokens[++i];
    } else if (token === '--dataset-file' && tokens[i + 1]) {
      parsed.datasetFile = tokens[++i];
    } else if (token === '--format' && tokens[i + 1]) {
      parsed.outputFormat = tokens[++i] as any;
    } else if (token === '--save-result' && tokens[i + 1]) {
      parsed.saveResult = tokens[++i];
    } else if (token === '--save-total-throughput-timeseries') {
      parsed.saveTotalThroughputTimeseries = true;
    } else if (token === '--save-all-throughput-timeseries') {
      parsed.saveAllThroughputTimeseries = true;
    } else if (token === '--exit-on-first-fail') {
      parsed.exitOnFirstFail = true;
    } else if (token === '--no-results-on-fail') {
      parsed.noResultsOnFail = true;
    } else if (token === '--verbose') {
      parsed.verbose = true;
    } else if (token === '--post-run-cmd' && tokens[i + 1]) {
      parsed.postRunCmd = tokens[++i].replace(/^"|"$/g, '');
    } else if (token === '--extra-body' && tokens[i + 1]) {
      parsed.extraBody = tokens[++i].replace(/^"|"$/g, '');
    }
    i++;
  }

  return parsed;
}
