import { BenchmarkResultRow } from '@/types/benchmark';

export function formatTps(val?: number, std?: number): string {
  if (val === undefined || isNaN(val)) return '—';
  const valStr = val >= 1000 ? val.toFixed(1) : val.toFixed(2);
  if (std !== undefined && !isNaN(std) && std > 0) {
    return `${valStr} ± ${std.toFixed(2)}`;
  }
  return valStr;
}

export function formatMs(val?: number, std?: number): string {
  if (val === undefined || isNaN(val)) return '—';
  const valStr = val.toFixed(2);
  if (std !== undefined && !isNaN(std) && std > 0) {
    return `${valStr} ± ${std.toFixed(2)} ms`;
  }
  return `${valStr} ms`;
}

export function formatTokens(num: number): string {
  if (num >= 1048576) return `${(num / 1048576).toFixed(1)}M`;
  if (num >= 1024) return `${(num / 1024).toFixed(0)}k`;
  return num.toString();
}

/**
 * Parses markdown table generated by llama-benchy into structured BenchmarkResultRow[]
 */
export function parseLlamaBenchMarkdown(md: string): BenchmarkResultRow[] {
  const rows: BenchmarkResultRow[] = [];
  const lines = md.split('\n');

  let inTable = false;
  let headers: string[] = [];

  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed.startsWith('|')) continue;

    const cells = trimmed
      .split('|')
      .slice(1, -1)
      .map(c => c.trim());

    if (cells.length < 3) continue;

    // Check if header separator line
    if (cells.every(c => /^:?-+:?$/.test(c))) {
      inTable = true;
      continue;
    }

    if (!inTable) {
      headers = cells.map(h => h.toLowerCase());
      continue;
    }

    // Row data
    const rowObj: Record<string, string> = {};
    cells.forEach((cell, idx) => {
      if (headers[idx]) {
        rowObj[headers[idx]] = cell;
      }
    });

    const model = rowObj['model'] || 'Unknown Model';
    const test = rowObj['test'] || '';
    const tpsRaw = rowObj['t/s'] || rowObj['tps'] || '';
    const peakTpsRaw = rowObj['peak t/s'] || '';
    const ttfrRaw = rowObj['ttfr (ms)'] || '';
    const estPptRaw = rowObj['est_ppt (ms)'] || '';
    const e2eTtftRaw = rowObj['e2e_ttft (ms)'] || '';

    const parseValueStd = (str: string) => {
      if (!str || str === '—' || str === '-') return { val: undefined, std: undefined };
      const parts = str.split('±').map(p => parseFloat(p.trim().replace(/ms/g, '')));
      return {
        val: isNaN(parts[0]) ? undefined : parts[0],
        std: parts[1] !== undefined && !isNaN(parts[1]) ? parts[1] : undefined,
      };
    };

    const tpsParsed = parseValueStd(tpsRaw);
    const peakTpsParsed = parseValueStd(peakTpsRaw);
    const ttfrParsed = parseValueStd(ttfrRaw);
    const estPptParsed = parseValueStd(estPptRaw);
    const e2eTtftParsed = parseValueStd(e2eTtftRaw);

    // Extract pp, tg, depth from test string (e.g. "pp2048 @ d4096", "tg32 @ d8192 c4")
    let pp = 0;
    let tg = 0;
    let depth = 0;
    let concurrency = 1;

    const ppMatch = test.match(/pp(\d+)/i);
    if (ppMatch) pp = parseInt(ppMatch[1], 10);

    const tgMatch = test.match(/tg(\d+)/i);
    if (tgMatch) tg = parseInt(tgMatch[1], 10);

    const depthMatch = test.match(/d(\d+)/i);
    if (depthMatch) depth = parseInt(depthMatch[1], 10);

    const concMatch = test.match(/c(\d+)/i);
    if (concMatch) concurrency = parseInt(concMatch[1], 10);

    rows.push({
      id: `row-${Math.random().toString(36).substring(2, 9)}`,
      model,
      test,
      pp,
      tg,
      depth,
      concurrency,
      tps: tpsParsed.val || 0,
      tpsStd: tpsParsed.std,
      peakTps: peakTpsParsed.val,
      peakTpsStd: peakTpsParsed.std,
      ttfrMs: ttfrParsed.val,
      ttfrStd: ttfrParsed.std,
      estPptMs: estPptParsed.val,
      estPptStd: estPptParsed.std,
      e2eTtftMs: e2eTtftParsed.val,
      e2eTtftStd: e2eTtftParsed.std,
      rawText: trimmed,
    });
  }

  return rows;
}
