import { BenchmarkConfig, BenchmarkResultRow } from '@/types/benchmark';
import { formatTps, formatMs } from '@/utils/formatters';

export function calculateSummaryMetrics(rows: BenchmarkResultRow[]) {
  const ppRows = rows.filter((r) => r.pp > 0);
  const tgRows = rows.filter((r) => r.tg > 0 && r.tps > 0);
  const ttfrRows = rows.filter((r) => r.ttfrMs !== undefined && r.ttfrMs > 0);

  // Compute Prefill Throughput from (pp + depth) / (ttfrMs / 1000)
  const prefillSpeeds = ppRows.map((r) => {
    if (r.ttfrMs && r.ttfrMs > 0) {
      const totalPromptTokens = r.pp + r.depth;
      return totalPromptTokens / (r.ttfrMs / 1000);
    }
    return r.tps;
  }).filter((v) => v > 0);

  const avgPpTps =
    prefillSpeeds.length > 0
      ? prefillSpeeds.reduce((acc, v) => acc + v, 0) / prefillSpeeds.length
      : 0;

  const avgTgTps =
    tgRows.length > 0 ? tgRows.reduce((acc, r) => acc + r.tps, 0) / tgRows.length : 0;

  const avgTtfrMs =
    ttfrRows.length > 0
      ? ttfrRows.reduce((acc, r) => acc + (r.ttfrMs || 0), 0) / ttfrRows.length
      : 0;

  const peakTps = rows.reduce(
    (max, r) => Math.max(max, r.peakTps || r.tps || 0),
    0
  );

  return {
    avgPpTps,
    avgTgTps,
    avgTtfrMs,
    peakTps,
    totalShapes: rows.length,
    ppCount: ppRows.length,
    tgCount: tgRows.length,
  };
}

export function generateStructuredMarkdownReport(
  config: BenchmarkConfig,
  rows: BenchmarkResultRow[],
  logs?: string[]
): string {
  const summary = calculateSummaryMetrics(rows);
  const dateStr = new Date().toLocaleString();
  const modelName = config.model || config.servedModelName || (rows[0]?.model) || 'Unknown Model';

  const ppRows = rows.filter((r) => r.pp > 0);
  const tgRows = rows.filter((r) => r.tg > 0);
  const uniqueConcurrencies = Array.from(new Set(rows.map((r) => r.concurrency))).sort((a, b) => a - b);

  let md = `# ⚡ LLM Inference Benchmark Report
> Generated by **AI-Benchy** wrapping [llama-benchy](https://github.com/eugr/llama-benchy)  
> **Date & Time:** ${dateStr}

---

## 📌 Executive Summary

| Benchmark Metric | Result | Details |
|:---|---:|:---|
| **Model Name** | \`${modelName}\` | Target inference model |
| **Endpoint URL** | \`${config.baseUrl}\` | OpenAI-compatible endpoint |
| **Avg Prompt Processing (PP)** | **${formatTps(summary.avgPpTps)} t/s** | Average prefill throughput (${summary.ppCount} shapes) |
| **Avg Token Generation (TG)** | **${formatTps(summary.avgTgTps)} t/s** | Average decoding throughput (${summary.tgCount} shapes) |
| **Avg TTFR Latency** | **${formatMs(summary.avgTtfrMs)}** | Time to first response chunk |
| **Peak Decode Throughput** | **${formatTps(summary.peakTps)} t/s** | Maximum measured tokens/sec |
| **Total Test Shapes** | **${summary.totalShapes} configurations** | Matrix combinations tested |

---

`;

  // 1. Prompt Processing Section
  if (ppRows.length > 0) {
    md += `## 📊 1. Prompt Processing (Prefill) Scaling Analysis

Prompt Processing speed (tokens/sec) measured across input sequence lengths and context depths:

| Test Shape | Prompt Tokens | Context Depth | Concurrency | Calculated Prefill (t/s) | TTFR (ms) | Est. PPT (ms) | E2E TTFT (ms) |
|:---|---:|---:|---:|---:|---:|---:|---:|
`;
    for (const r of ppRows) {
      const calculatedPrefill = (r.ttfrMs && r.ttfrMs > 0)
        ? (r.pp + r.depth) / (r.ttfrMs / 1000)
        : r.tps;
      md += `| \`${r.test}\` | ${r.pp} | ${r.depth} | ${r.concurrency} | **${formatTps(calculatedPrefill)}** | ${formatMs(r.ttfrMs, r.ttfrStd)} | ${formatMs(r.estPptMs, r.estPptStd)} | ${formatMs(r.e2eTtftMs, r.e2eTtftStd)} |\n`;
    }
    md += '\n---\n\n';
  }

  // 2. Token Generation Section
  if (tgRows.length > 0) {
    md += `## ⚡ 2. Token Generation (Decode) Scaling Analysis

Autoregressive token generation speed (tokens/sec) measured across output lengths and context depths:

| Test Shape | Gen Tokens | Context Depth | Concurrency | Decode Speed (t/s) | Peak Speed (t/s) |
|:---|---:|---:|---:|---:|---:|
`;
    for (const r of tgRows) {
      md += `| \`${r.test}\` | ${r.tg} | ${r.depth} | ${r.concurrency} | **${formatTps(r.tps, r.tpsStd)}** | ${formatTps(r.peakTps, r.peakTpsStd)} |\n`;
    }
    md += '\n---\n\n';
  }

  // 3. Concurrency Scaling Section (if multiple concurrencies tested)
  if (uniqueConcurrencies.length > 1) {
    md += `## 👥 3. Multi-Client Concurrency Scaling Analysis

Comparison of serving throughput as concurrent client requests scale:

| Concurrency (Clients) | Avg PP Speed (t/s) | Avg TG Speed (t/s) | Scaling Factor |
|---:|---:|---:|---:|
`;
    const baselineConc = uniqueConcurrencies[0];
    const baseTg = tgRows.filter((r) => r.concurrency === baselineConc).reduce((a, b) => a + b.tps, 0) / (tgRows.filter((r) => r.concurrency === baselineConc).length || 1);

    for (const conc of uniqueConcurrencies) {
      const concPp = ppRows.filter((r) => r.concurrency === conc);
      const concTg = tgRows.filter((r) => r.concurrency === conc);
      const avgPp = concPp.length > 0 ? concPp.reduce((a, b) => a + b.tps, 0) / concPp.length : 0;
      const avgTg = concTg.length > 0 ? concTg.reduce((a, b) => a + b.tps, 0) / concTg.length : 0;
      const scalingFactor = baseTg > 0 ? (avgTg / baseTg).toFixed(2) + 'x' : '—';

      md += `| ${conc} | ${formatTps(avgPp)} | ${formatTps(avgTg)} | **${scalingFactor}** |\n`;
    }
    md += '\n---\n\n';
  }

  // 4. Consolidated Matrix Table
  md += `## 📋 4. Full Consolidated Benchmark Matrix (\`llama-bench\` Format)

\`\`\`
| model | test | t/s | peak t/s | ttfr (ms) | est_ppt (ms) | e2e_ttft (ms) |
|:---|---:|---:|---:|---:|---:|---:|
`;
  for (const r of rows) {
    md += `| ${r.model} | ${r.test} | ${formatTps(r.tps, r.tpsStd)} | ${formatTps(r.peakTps, r.peakTpsStd)} | ${formatMs(r.ttfrMs, r.ttfrStd)} | ${formatMs(r.estPptMs, r.estPptStd)} | ${formatMs(r.e2eTtftMs, r.e2eTtftStd)} |\n`;
  }
  md += `\`\`\`\n\n---\n\n`;

  // 5. Execution Environment & Configuration Metadata
  md += `## ⚙️ 5. Benchmark Configuration & Parameters

- **Inference Endpoint:** \`${config.baseUrl}\`
- **Model Identifier:** \`${modelName}\`
- **Served Model Name:** \`${config.servedModelName || modelName}\`
- **Tokenizer:** \`${config.tokenizer || 'Auto-detected / Fallback'}\`
- **Prompt Token Counts (\`--pp\`):** \`[${config.pp.join(', ')}]\`
- **Generation Token Counts (\`--tg\`):** \`[${config.tg.join(', ')}]\`
- **Context Depth Counts (\`--depth\`):** \`[${config.depth.join(', ')}]\`
- **Concurrency Levels (\`--concurrency\`):** \`[${config.concurrency.join(', ')}]\`
- **Runs per Configuration (\`--runs\`):** \`${config.runs}\`
- **Warmup Runs (\`--warmup-runs\`):** \`${config.warmupRuns}\`
- **Latency Measurement Mode (\`--latency-mode\`):** \`${config.latencyMode}\`
- **Prefix Caching Enabled (\`--enable-prefix-caching\`):** \`${config.enablePrefixCaching ? 'Yes' : 'No'}\`
- **Exact Generation Length (\`--exact-tg\`):** \`${config.exactTg ? 'Yes' : 'No'}\`
- **Tool Version:** \`llama-benchy 0.4.1\`

---
*Report generated automatically by [AI-Benchy](https://github.com/eugr/llama-benchy).*
`;

  return md;
}
